Template.atResendVerificationEmailLink.helpers AccountsTemplates.atResendVerificationEmailLinkHelpers
Template.atResendVerificationEmailLink.events AccountsTemplates.atResendVerificationEmailLinkEvents
